apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: helm
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-container
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          ports:
            - name: port-1
              containerPort: 5672
            - name: port-2
              containerPort: 15672
             
          